import { useEffect, useState } from 'react'
import Head from 'next/head'
import { Typography, Grid, Box } from '@mui/material'
import ProjectCard from '../components/ProjectCard'
import ToolStrip from '../components/ToolStrip'
import ExperienceStrip from '../components/ExperienceStrip'
import { collection, getDocs } from 'firebase/firestore'
import { db } from '../backend/firebase'
import { useTheme } from "next-themes";
import { Globals } from "@react-spring/shared";
import { Canvas } from '@react-three/fiber'
import Model from '../components/Avatar'
import { OrbitControls } from '@react-three/drei'
import Link from 'next/link'
import Nav from '../components/Nav'

export default function Home() {

  const [projects, setProjects] = useState([])
  const [experiences, setExperiences] = useState([])

  const fetchProject = async () => {
    const query = collection(db, `projects`)
    const resData = await getDocs(query)
    setProjects([])
    resData.docs.forEach(doc => {
      setProjects(projects => [...projects, doc.data()])
    })
  }
  const fetchExperience = async () => {
    const query = collection(db, `experiences
    `)
    const resData = await getDocs(query)
    resData.docs.forEach(doc => {
      setExperiences(experience => [...experience, doc.data()])
    })
  }

  useEffect(() => {
    fetchProject()
    fetchExperience()
  }, [])


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />

      <Grid container sx={{ display: 'flex', flexDirection: 'column', maxWidth: '100vw', overflowX: 'hidden' }}>
        <Grid item sx={{ minHeight: '100vh', position: 'relative', display: 'flex', flexDirection: 'row', justifyContent: 'space-evenly', alignItems: 'center' }}>
          {/* <Landing /> */}
          {/* <Grid sx={{ height: '100vh', width: '100%', backdropFilter: 'blur(2px)', position: 'absolute', top: 0, display: 'flex', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }}> */}
          <Box sx={{ minWidth: '400px' }}>
            <Typography variant='h2' sx={{ margin: 'auto' }}>Hii👋👋</Typography>
            <Typography variant='h3' sx={{ margin: 'auto' }}>I'm Sreeroop</Typography>
          </Box>
          <Box sx={{ minWidth: '400px', minHeight: '400px' }}>
            <Canvas
              camera={{ position: [1, 1, 10], fov: 60 }}
              style={{ width: '400px', height: '400px' }}>
              <ambientLight intensity={0.3} />
              {/* Our main source of light, also casting our shadow */}
              <directionalLight
                castShadow
                position={[10, 10, 10]}
                intensity={0.5}
                shadow-mapSize-width={1024}
                shadow-mapSize-height={1024}
                shadow-camera-far={50}
                shadow-camera-left={-10}
                shadow-camera-right={10}
                shadow-camera-top={10}
                shadow-camera-bottom={-10}
              />
              {/* A light to help illumnate the spinning boxes */}
              <pointLight position={[-10, 10, 10]} intensity={0.5} />
              <pointLight position={[10, -10, 0]} intensity={0.5} />
              <Model />
              <OrbitControls />
            </Canvas>

          </Box>

          {/* </Grid> */}
        </Grid>

        <Grid item sx={{ minHeight: '10vh', width: '110vw', margin: 'auto', textAlign: 'center' }}>
          <Typography variant='h3' sx={{ margin: 'auto' }}>My Experience</Typography>
          {
            experiences.map((experience, index) => {
              return <ExperienceStrip key={index} data={experience} />
            })
          }
        </Grid>
        <Grid item sx={{ minHeight: '100vh', width: '110vw', margin: 'auto' }}>
          <ToolStrip />
        </Grid>

        <Grid item sx={{ minHeight: '100vh', width: '100vw', alignItems: 'center', padding: '20px', display: 'flex', alignItems: 'center', flexWrap: 'wrap', justifyContent: 'space-around', flexDirection: 'column', }}>
          <Typography variant='h3' sx={{ margin: 'auto' }}>My Projects</Typography>
          <Grid sx={{ display: 'flex', alignItems: 'center', flexWrap: 'wrap', justifyContent: 'space-around', flexDirection: 'row', }}>
            {
              projects.map(project => {
                return <ProjectCard key={project?.slug} data={project} />
              })
            }
          </Grid>
        </Grid>


      </Grid >
    </>
  )
}
